{
  "formatVersion": "1.1",
  "component": {
    "group": "coder.siy",
    "module": "exclude-dependencies-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "exclude-dependencies-plugin-1.0.0.jar",
          "url": "exclude-dependencies-plugin-1.0.0.jar",
          "size": 32982,
          "sha512": "d832fd96b3615e730863c8ceae25b7613c219477c96d3a9cb0be6ce704c3b58d2c8d93bdf0901e5cb5ff78ed6c6e97ce2b6de0e7affd0174c25c4da7c1198491",
          "sha256": "8ed770445198a7f451dd61b66a5c799ad29e8b53a65e539dbb8a05fbef318e40",
          "sha1": "dd36b33ae875e86105e197fc22cdc9fc8cfb2998",
          "md5": "acb93e34bd408713794795674d5369ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "exclude-dependencies-plugin-1.0.0.jar",
          "url": "exclude-dependencies-plugin-1.0.0.jar",
          "size": 32982,
          "sha512": "d832fd96b3615e730863c8ceae25b7613c219477c96d3a9cb0be6ce704c3b58d2c8d93bdf0901e5cb5ff78ed6c6e97ce2b6de0e7affd0174c25c4da7c1198491",
          "sha256": "8ed770445198a7f451dd61b66a5c799ad29e8b53a65e539dbb8a05fbef318e40",
          "sha1": "dd36b33ae875e86105e197fc22cdc9fc8cfb2998",
          "md5": "acb93e34bd408713794795674d5369ba"
        }
      ]
    }
  ]
}
